baseURL = "https://hackinister.github.io"
# baseurl      = 'https://blog.hackinister,is-a.dev'
title        = 'blog.hackinister.is-a.dev'
languageCode = "de-de"
theme        = "hello-4s3ti"
IsMultiLingual = false
pagination.pagerSize = 10
defaultContentLanguage = "de"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04"

  defaultTheme = "dark"
  EnableThemeToggle = true

  backgroundImage= "static/coolapso.webp"
  backgroundEffects = true
  
  tags = true
  ReadMoreText = false

  ShowReadingTime = false
  LastModDisplay = true

  fontAwesome = { all = true}
  logo = { logoText = "hackinister", logoCursorColor = "#ffffff" }

  # Subtitle for home
  #homeSubtitle = "A simple and beautiful blog"
  showPosts = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  footer = { showVersion = true, socialIcons = true, rss = true, bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>", "with <a href=\"https://github.com/coolapso/hugo-theme-hello-4s3ti\">Hello-friend-4s3ti</a>"] }

  # Metadata mostly used in document's head
  description = "Meiner erster Blog"
  keywords = "homepage, blog"
  images = [""]
  
[[params.social]]
  name = "github"
  url = "https://github.com/hackinister"


[taxonomies]
    category = "blog"
    tag      = "tags"

[languages]
  [languages.de]
    title = "hackinister"
    subtitle = "Der erste eigene Blog"
    keywords = ""
    readOtherPosts = "Lese weitere Posts"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
    weight = 1



